'use client';
import { useState } from 'react';
import { UserPlus } from 'lucide-react';
import Link from 'next/link';
import { createClient } from '../../../lib/supabase';
import { Avatar } from '../../../components/avatar';

const presets=['default:campus','default:drop','default:green','default:classic'];
export default function Register(){
  const [name,setName]=useState(''); const [campus,setCampus]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [avatar,setAvatar]=useState('default:campus'); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError('');setNotice('');const cleanName=name.trim().slice(0,80),cleanCampus=campus.trim().slice(0,120);if(!cleanName||!cleanCampus){setError('Full name and campus are required.');setLoading(false);return}const supabase=createClient();const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:cleanName,campus:cleanCampus,avatar_url:avatar}}});if(error)setError(error.message);else if(data.session)location.href='/marketplace';else setNotice('Account created. Check your email if email confirmation is enabled.');setLoading(false)}
  return <main className="formPage"><div className="formCard"><img src="/campusdrop-logo.png" style={{width:120,height:78,objectFit:'contain',objectPosition:'left center'}} alt="CampusDrop logo"/><h1>Create account</h1><p className="muted">Join students buying and selling on campus.</p>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<form onSubmit={submit}><div className="field"><label htmlFor="fullName">Full name</label><input id="fullName" value={name} maxLength={80} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label htmlFor="campus">Campus</label><input id="campus" value={campus} maxLength={120} placeholder="Your school / campus" onChange={e=>setCampus(e.target.value)} required/></div><div className="field"><label>Default avatar</label><div className="avatarChoices registerChoices">{presets.map(p=><button key={p} type="button" className={`avatarChoice ${avatar===p?'selected':''}`} aria-pressed={avatar===p} aria-label={`Choose ${p.replace('default:','')} avatar`} onClick={()=>setAvatar(p)}><Avatar url={p} size="md" /></button>)}</div></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><div className="muted fieldHint">Use at least 8 characters.</div></div><button className="btn green full" disabled={loading}><UserPlus size={17}/>{loading?'Creating...':'Create account'}</button></form><p className="muted" style={{marginTop:20}}>Already registered? <Link href="/auth/login" className="textLink">Sign in</Link></p></div></main>
}
