'use client';
import { useEffect, useState } from 'react';
import { UserPlus } from 'lucide-react';
import Link from 'next/link';
import { createClient } from '../../../lib/supabase';
import { Avatar } from '../../../components/avatar';
import PasswordStrength, { passwordScore } from '../../../components/password-strength';

const presets=['default:campus','default:drop','default:green','default:classic'];
const COOLDOWN_MS=8000;
export default function Register(){
  const [name,setName]=useState(''); const [campus,setCampus]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [avatar,setAvatar]=useState('default:campus'); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false); const [cooldown,setCooldown]=useState(0);
  useEffect(()=>{const until=Number(localStorage.getItem('campusdrop-register-cooldown')||0);if(until>Date.now())setCooldown(Math.ceil((until-Date.now())/1000));},[]);
  useEffect(()=>{if(cooldown<=0)return;const t=setInterval(()=>setCooldown(Math.max(0,Math.ceil((Number(localStorage.getItem('campusdrop-register-cooldown')||0)-Date.now())/1000))),500);return()=>clearInterval(t)},[cooldown]);
  function beginCooldown(){const until=Date.now()+COOLDOWN_MS;localStorage.setItem('campusdrop-register-cooldown',String(until));setCooldown(Math.ceil(COOLDOWN_MS/1000));}
  async function submit(e:React.FormEvent){e.preventDefault();if(loading||cooldown>0)return;setLoading(true);setError('');setNotice('');beginCooldown();const cleanName=name.trim().slice(0,80),cleanCampus=campus.trim().slice(0,120);if(!cleanName||!cleanCampus){setError('Full name and campus are required.');setLoading(false);return}if(passwordScore(password)<5){setError('Please choose a stronger password that meets all requirements.');setLoading(false);return}const supabase=createClient();const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:cleanName,campus:cleanCampus,avatar_url:avatar}}});if(error)setError(error.message);else if(data.session)location.href='/marketplace';else setNotice('Account created. Check your email to verify your account before signing in.');setLoading(false)}
  async function google(){if(loading||cooldown>0)return;setLoading(true);setError('');beginCooldown();const {error}=await createClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback?next=/marketplace`}});if(error){setError(error.message);setLoading(false)}}
  return <main className="formPage"><div className="formCard"><img src="/campusdrop-logo.png" style={{width:140,height:78,objectFit:'contain',objectPosition:'left center'}} alt="CampusDrop logo"/><h1>Create account</h1><p className="muted">Join students buying and selling on campus.</p>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
    <button type="button" className="btn light full googleButton" onClick={google} disabled={loading||cooldown>0}><span className="googleMark">G</span>{loading?'Connecting...':'Continue with Google'}</button><div className="authDivider"><span>or create with email</span></div>
    <form onSubmit={submit}><div className="field"><label htmlFor="fullName">Full name</label><input id="fullName" value={name} maxLength={80} onChange={e=>setName(e.target.value)} required autoComplete="name"/></div><div className="field"><label htmlFor="campus">Campus</label><input id="campus" value={campus} maxLength={120} placeholder="Your school / campus" onChange={e=>setCampus(e.target.value)} required/></div><div className="field"><label>Default avatar</label><div className="avatarChoices registerChoices">{presets.map(p=><button key={p} type="button" className={`avatarChoice ${avatar===p?'selected':''}`} aria-pressed={avatar===p} aria-label={`Choose ${p.replace('default:','')} avatar`} onClick={()=>setAvatar(p)}><Avatar url={p} size="md" /></button>)}</div></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="new-password"/><PasswordStrength password={password}/></div><button className="btn green full" disabled={loading||cooldown>0}><UserPlus size={17}/>{loading?'Creating...':'Create account'}</button></form>
    <p className="muted" style={{marginTop:20}}>Already registered? <Link href="/auth/login" className="textLink">Sign in</Link></p>
  </div></main>
}
