'use client';
import {useEffect,useState} from 'react';
import {CheckCircle2,ShieldCheck,Trash2,XCircle,Send,BadgeCheck,ExternalLink} from 'lucide-react';
import {createClient} from '../../lib/supabase';
import {Skeleton} from '../../components/skeleton';
export default function Admin(){const [reports,setReports]=useState<any[]>([]),[verifications,setVerifications]=useState<any[]>([]),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[actionId,setActionId]=useState<string|null>(null),[error,setError]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[sending,setSending]=useState(false),[broadcastResult,setBroadcastResult]=useState('');
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.assign('/auth/login?next=/admin');return}const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin'){setLoading(false);return}setAllowed(true);const [{data:r,error:re},{data:v,error:ve}]=await Promise.all([s.from('reports').select('*,listings(title,status)').eq('status','pending').order('created_at',{ascending:false}),s.from('student_verifications').select('*').eq('status','pending').order('submitted_at',{ascending:false})]);if(re||ve)setError((re||ve)?.message||'Could not load admin data.');setReports(r||[]);setVerifications(v||[]);setLoading(false)}useEffect(()=>{load()},[]);
 async function action(report:any,status:'removed'|'dismissed'){setActionId(report.id);const s=createClient();try{if(status==='removed'){const {error:e}=await s.from('listings').update({status:'hidden'}).eq('id',report.listing_id);if(e)throw e}const {data:{user}}=await s.auth.getUser();const {error:e}=await s.from('reports').update({status,reviewed_by:user?.id||null,reviewed_at:new Date().toISOString()}).eq('id',report.id);if(e)throw e;setReports(x=>x.filter(r=>r.id!==report.id))}catch(e:any){setError(e.message||'Moderation action failed.')}finally{setActionId(null)}}
 async function review(v:any,status:'approved'|'rejected'){setActionId(v.id);const s=createClient();const {data:{user}}=await s.auth.getUser();const {error:e}=await s.from('student_verifications').update({status,reviewed_by:user?.id||null,reviewed_at:new Date().toISOString(),rejection_reason:status==='rejected'?'Document could not be verified.':null}).eq('id',v.id);if(e)setError(e.message);else setVerifications(x=>x.filter(i=>i.id!==v.id));setActionId(null)}
 async function openDocument(path:string){const {data,error:e}=await createClient().storage.from('verification-documents').createSignedUrl(path,300);if(e){setError(e.message);return}if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')} async function broadcast(evt:React.FormEvent){evt.preventDefault();if(!title.trim()||!body.trim())return;setSending(true);setBroadcastResult('');const {data,error:rpcError}=await createClient().rpc('admin_broadcast_notification',{p_title:title.trim(),p_body:body.trim(),p_type:'admin_broadcast'});if(rpcError)setError(rpcError.message);else{setBroadcastResult(`Announcement sent to ${data} users.`);setTitle('');setBody('')}setSending(false)}
 if(loading)return <main className="section"><div className="container"><Skeleton className="skeletonLine"/><Skeleton className="skeletonLine medium"/></div></main>;
 if(!allowed)return <main className="section"><div className="container"><div className="empty"><ShieldCheck size={30}/><h2>Admin access required</h2><p>Promote a trusted account to role <b>admin</b> in Supabase before using this area.</p></div></div></main>;
 return <main className="section"><div className="container"><div className="eyebrow">Moderation & communications</div><h1>Admin dashboard</h1>{error&&<div className="error">{error}</div>}\n <section className="panel adminBroadcast"><h2>Broadcast notification</h2><p className="muted">Send an announcement to every CampusDrop user.</p><form onSubmit={broadcast}><div className="field"><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={180} placeholder="CampusDrop announcement" required/></div><div className="field"><label>Message</label><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder="Write your announcement..." required/></div><button className="btn green" disabled={sending}><Send size={16}/>{sending?'Sending...':'Send to all users'}</button>{broadcastResult&&<div className="notice" style={{marginTop:12}}>{broadcastResult}</div>}</form></section>\n <section className="panel adminQueue"><div className="sectionHead"><div><h2>Student verification</h2><p className="muted">Review student ID or current enrolment documents.</p></div></div>{!verifications.length?<div className="empty"><BadgeCheck size={28}/><p>No pending verification requests.</p></div>:verifications.map(v=><div className="noticeRow adminReport" key={v.id}><ShieldCheck size={20}/><div className="adminReportCopy"><b>{v.institution} · {v.campus}</b><div className="muted">User: {v.user_id} · {v.department||'Department not provided'} · {v.level||'Level not provided'}</div><button type="button" className="linkButton muted" onClick={()=>openDocument(v.document_path)}><ExternalLink size={14}/> Open document</button></div><button className="btn green" disabled={actionId===v.id} onClick={()=>review(v,'approved')}><CheckCircle2 size={16}/> Approve</button><button className="btn danger" disabled={actionId===v.id} onClick={()=>review(v,'rejected')}><XCircle size={16}/> Reject</button></div>)}</section>\n <section className="panel adminQueue"><div className="sectionHead"><div><h2>Reports</h2></div></div>{!reports.length?<div className="empty"><CheckCircle2 size={30}/><p>No pending reports.</p></div>:reports.map(r=><div className="noticeRow adminReport" key={r.id}><ShieldCheck size={20}/><div className="adminReportCopy"><b>{r.listings?.title||'Listing'}</b><div className="muted">{r.reason} · {new Date(r.created_at).toLocaleString()}</div></div><button className="btn danger" disabled={actionId===r.id} onClick={()=>action(r,'removed')}><Trash2 size={16}/> Remove</button><button className="btn light" disabled={actionId===r.id} onClick={()=>action(r,'dismissed')}><XCircle size={16}/> Dismiss</button></div>)}</section></div></main>}
