'use client';
import { useEffect, useState } from 'react';
import { CheckCircle2, ShieldCheck } from 'lucide-react';
import { createClient } from '../../../lib/supabase';
import { Avatar } from '../../../components/avatar';
import { PageSkeleton } from '../../../components/skeleton';

export default function CompleteProfile() {
  const [user,setUser]=useState<any>(null); const [name,setName]=useState(''); const [campus,setCampus]=useState(''); const [location,setLocation]=useState(''); const [phone,setPhone]=useState(''); const [whatsapp,setWhatsapp]=useState(''); const [avatar,setAvatar]=useState('default:campus'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.assign('/auth/login');return}setUser(user);const [{data:p},{data:pp}]=await Promise.all([s.from('profiles').select('full_name,campus,location,avatar_url').eq('id',user.id).maybeSingle(),s.from('profile_private').select('phone,whatsapp').eq('user_id',user.id).maybeSingle()]);setName(p?.full_name||user.user_metadata?.full_name||user.user_metadata?.name||'');setCampus(p?.campus||user.user_metadata?.campus||'');setLocation(p?.location||'');setAvatar(p?.avatar_url||user.user_metadata?.avatar_url||user.user_metadata?.picture||'default:campus');setPhone(pp?.phone||'');setWhatsapp(pp?.whatsapp||'');setLoading(false)})()},[]);
  async function save(e:React.FormEvent){e.preventDefault();if(!user||saving)return;setSaving(true);setError('');const s=createClient();const {error:pe}=await s.from('profiles').update({full_name:name.trim().slice(0,80),campus:campus.trim().slice(0,120),location:location.trim().slice(0,160)||null,avatar_url:avatar}).eq('id',user.id);if(pe){setError(pe.message);setSaving(false);return}const {error:pr}=await s.from('profile_private').upsert({user_id:user.id,phone:phone.trim().slice(0,30)||null,whatsapp:whatsapp.trim().slice(0,30)||null},{onConflict:'user_id'});if(pr){setError(pr.message);setSaving(false);return}const next=new URLSearchParams(window.location.search).get('next')||'/marketplace';window.location.assign(next.startsWith('/')&&!next.startsWith('//')?next:'/marketplace')}
  if(loading)return <main className="formPage"><PageSkeleton rows={6}/></main>;
  return <main className="formPage"><div className="formCard"><div className="row"><Avatar url={avatar} name={name||'Student'} size="lg"/><div><div className="eyebrow">One last step</div><h1 style={{margin:'5px 0'}}>Complete your profile</h1><p className="muted">Google has supplied your basic identity. Add your campus details before entering CampusDrop.</p></div></div>{error&&<div className="error">{error}</div>}<form onSubmit={save}><div className="field"><label>Full name</label><input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></div><div className="field"><label>Email</label><input value={user?.email||''} readOnly /></div><div className="field"><label>Campus / institution</label><input value={campus} onChange={e=>setCampus(e.target.value)} required maxLength={120} placeholder="e.g. TASUED"/></div><div className="field"><label>Location <span className="muted">(public)</span></label><input value={location} onChange={e=>setLocation(e.target.value)} required maxLength={160} placeholder="e.g. Ijebu-Ode"/></div><div className="privateContactBox"><div className="privateContactHead"><ShieldCheck size={18}/><div><b>Private contact details</b><p className="muted">Optional. Other students cannot view these values.</p></div></div><div className="privateGrid"><div className="field"><label>Phone</label><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" maxLength={30}/></div><div className="field"><label>WhatsApp</label><input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} inputMode="tel" maxLength={30}/></div></div></div><button className="btn green full" disabled={saving}><CheckCircle2 size={17}/>{saving?'Saving profile...':'Continue to CampusDrop'}</button></form></div></main>;
}
