'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, Clock3, FileCheck2, ShieldCheck, Upload } from 'lucide-react';
import { createClient } from '../../lib/supabase';
import { PageSkeleton } from '../../components/skeleton';

export default function VerifyStudent(){
 const [user,setUser]=useState<any>(null); const [status,setStatus]=useState<any>(null); const [institution,setInstitution]=useState(''); const [campus,setCampus]=useState(''); const [department,setDepartment]=useState(''); const [level,setLevel]=useState(''); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/auth/login?next=/verify';return}setUser(user);const {data}=await s.from('student_verifications').select('*').eq('user_id',user.id).maybeSingle();setStatus(data);setLoading(false)})()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!user||saving||!file)return;setSaving(true);setError('');setNotice('');try{if(file.size>10*1024*1024)throw new Error('Verification document must be 10MB or smaller.');if(!file.type.startsWith('image/')&&file.type!=='application/pdf')throw new Error('Upload a JPG, PNG, WebP or PDF student document.');const s=createClient();const path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120)}`;const up=await s.storage.from('verification-documents').upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;const ins=await s.from('student_verifications').upsert({user_id:user.id,institution:institution.trim().slice(0,160),campus:campus.trim().slice(0,160),department:department.trim().slice(0,120)||null,level:level.trim().slice(0,50)||null,document_path:path,status:'pending',rejection_reason:null,submitted_at:new Date().toISOString(),reviewed_at:null,reviewed_by:null},{onConflict:'user_id'});if(ins.error)throw ins.error;setStatus({status:'pending',institution,campus,department,level});setNotice('Your document has been submitted. CampusDrop will review it before the badge is issued.')}catch(err:any){setError(err?.message||'Verification submission failed.')}finally{setSaving(false)}}
 if(loading)return <main className="section"><div className="container"><PageSkeleton rows={6}/></div></main>;
 const verified=status?.status==='approved'; const pending=status?.status==='pending';
 return <main className="section"><div className="container verifyPage"><div className="eyebrow">Trust & safety</div><h1>Verify your student status</h1><p className="muted verifyLead">Upload a current student ID or enrolment document. Your document is reviewed privately and is never displayed on your public profile.</p>{verified?<div className="panel verifyStatus approved"><CheckCircle2 size={28}/><div><h3>Verified Student</h3><p>You are verified at {status.institution}. Your badge can now appear on your CampusDrop profile and listings.</p></div></div>:pending?<div className="panel verifyStatus"><Clock3 size={28}/><div><h3>Verification pending</h3><p>Your submission is waiting for admin review.</p></div></div>:<form className="panel" onSubmit={submit}>{status?.status==='rejected'&&<div className="error">Previous submission was not approved. {status.rejection_reason||'Please submit a clearer current document.'}</div>}<div className="field"><label>Institution</label><input value={institution} onChange={e=>setInstitution(e.target.value)} required maxLength={160} placeholder="Tai Solarin University of Education"/></div><div className="field"><label>Campus</label><input value={campus} onChange={e=>setCampus(e.target.value)} required maxLength={160} placeholder="Main Campus"/></div><div className="split"><div className="field"><label>Department <span className="muted">(optional)</span></label><input value={department} onChange={e=>setDepartment(e.target.value)} maxLength={120}/></div><div className="field"><label>Level <span className="muted">(optional)</span></label><input value={level} onChange={e=>setLevel(e.target.value)} maxLength={50} placeholder="300 Level"/></div></div><div className="verifyUpload"><FileCheck2 size={24}/><div><b>Current student ID / enrolment document</b><p className="muted">JPG, PNG, WebP or PDF · maximum 10MB</p><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} required /></div></div>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<button className="btn green" disabled={saving||!file}><Upload size={17}/>{saving?'Submitting...':'Submit for verification'}</button></form>}<div className="panel verifyPrivacy"><ShieldCheck size={20}/><div><b>Your document stays private</b><p className="muted">Only authorised CampusDrop administrators can review the submitted document. The public badge only confirms verified student status.</p></div></div><Link href="/profile" className="textLink">Back to profile</Link></div></main>;
}
