'use client';
import {useEffect,useState} from 'react'; import Link from 'next/link'; import {Eye,Trash2,CheckCircle2,RotateCcw} from 'lucide-react'; import {createClient} from '../../lib/supabase'; import {Skeleton,CardSkeleton} from '../../components/skeleton';
export default function MyListings(){
 const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{const s=createClient();let mounted=true;let channel:any;let userId='';const load=async()=>{const {data:{user}}=await s.auth.getUser();if(!user){window.location.assign('/auth/login');return}userId=user.id;const {data}=await s.from('listings').select('*').eq('seller_id',user.id).neq('status','hidden').order('created_at',{ascending:false});if(mounted){setItems(data||[]);setLoading(false)}};load().then(()=>{if(!userId)return;channel=s.channel(`my-listings-${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'listings',filter:`seller_id=eq.${userId}`},()=>load()).subscribe()});return()=>{mounted=false;if(channel)s.removeChannel(channel)}},[]);
 async function hide(id:string){await createClient().from('listings').update({status:'hidden'}).eq('id',id)}
 async function toggle(i:any){const next=i.status==='available'?'sold':'available';await createClient().from('listings').update({status:next}).eq('id',i.id)}
 return <main className="section"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Seller centre</div><h1>My listings</h1></div><Link href="/sell" className="btn green">New listing</Link></div>{loading?<div className="grid">{[1,2,3].map(x=><CardSkeleton key={x}/>)}</div>:!items.length?<div className="empty">You have no listings yet.</div>:<div className="grid">{items.map(i=><div className="card" key={i.id}><div className="pic"/><div className="cardbody"><span className={`tag ${i.status==='sold'?'soldTag':''}`}>{i.status==='sold'?(i.listing_type==='accommodation'?'rented':'sold'):'available'}</span><h3>{i.title}</h3><div className="cardprice">₦{Number(i.price||0).toLocaleString()}</div><div className="actionsRow" style={{marginTop:12}}><Link className="btn light" href={'/product/'+i.id}><Eye size={16}/> View</Link><button className="btn light" onClick={()=>toggle(i)}>{i.status==='sold'?<RotateCcw size={16}/>:<CheckCircle2 size={16}/>} {i.status==='sold'?'Mark available':i.listing_type==='accommodation'?'Mark rented':'Mark sold'}</button><button className="btn danger" onClick={()=>hide(i.id)}><Trash2 size={16}/> Hide</button></div></div></div>)}</div>}</div></main>
}
